version: 2
jobs:
  # Job for building and deploying to GCP (production)
  deploy-gcp:
    environment:
      GCLOUD_PROJECT: vote-app-1
      SERVICE_VERSION: 1
    docker:
    - image: google/cloud-sdk
    steps:
    # Checkout project sources
    - checkout
    # Install NodeJS - latest 10.x.x version
    - run: curl -sL https://deb.nodesource.com/setup_10.x | bash -
    - run: apt-get install -y nodejs
    # Retrieve secrets from the CircleCI environment
    - run: echo $GCLOUD_SERVICE_KEY | base64 -di > ${HOME}/gcloud-service-key.json
    # Authenticate gcloud
    - run: gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    # Replace <your-project-id>
    - run: gcloud config set project $GCLOUD_PROJECT
               
workflows:
  version: 2
  # Deploy workflow
  deploy:
    jobs:
      - deploy-gcp:
          filters:
            branches:
              only:
                - master